#!/bin/bash

print_and_run() {
   echo -e "\033[36m** Casting spell **\033[0m"
   echo -e "\033[36m$*\033[0m"   # Print command in cyan
   echo "** * * * * * * * **"
   echo ""
   "$@"                           # Execute command safely
   echo -e "\033[1;35m$*\033[0m"   # Print command in cyan
   echo -e "\033[1;35m** spell finished **\033[0m"
}

script_name=$(basename "$0")
print_usage() 
{
   echo "Usage:"
   echo "  arg1 [e]xisting/[n]ew/[o]thers/[reset]"
   echo "  arg2 <branch name>, e.g. feature/xxx"
   echo ""
   echo "Example:"
   echo "gc e feature/xxx -> git checkout feature/xxx"
   echo "gc n feature/xxx -> git checkout -b feature/xxx"
   echo "gc o feature/xxx -> git checkout -b feature/xxx origin/feature/xxx"
   echo "gc reset feature/xxx -> git reset --hard origin/feature/xxx"
   echo ""
}

# Check for first argument
if [[ -z "$1" ]]; then
   print_usage
   exit 1
fi

proj=$1
branch_name=$2

if [ -z "$branch_name" ]; then
   echo "Hark! An error doth arise:"
   echo ""
   print_usage
   exit 1
else
   if [[ "$proj" == "o" ]]; then
      print_and_run git fetch origin $branch_name
      print_and_run git checkout -b $branch_name origin/$branch_name
      print_and_run git submodule update --init --recursive
   elif [[ "$proj" == "n" ]]; then
      print_and_run git checkout -b $branch_name
   elif [[ "$proj" == "e" ]]; then
      print_and_run git fetch origin $branch_name
      print_and_run git checkout $branch_name
      print_and_run git submodule update --init --recursive
   elif [[ "$proj" == "reset" ]]; then
      print_and_run git fetch origin $branch_name
      print_and_run git reset --hard origin/$branch_name
      print_and_run git clean -fdx
      print_and_run git submodule foreach --recursive "git reset --hard && git clean -fdx"
      print_and_run git submodule update --init --recursive
   else
      echo "Hark! An error doth arise:"
      echo ""
      print_usage
      exit 1
   fi
fi
