#!/bin/bash

print_and_run() {
   echo -e "\033[36m** Casting spell **\033[0m"
   echo -e "\033[36m$*\033[0m"   # Print command in cyan
   echo "** * * * * * * * **"
   echo ""
   "$@"                           # Execute command safely
   echo -e "\033[1;35m$*\033[0m"   # Print command in cyan
   echo -e "\033[1;35m** spell finished **\033[0m"
}

script_name=$(basename "$0")
print_usage() 
{
   echo "Usage: List branches"
   echo "  arg1 [m]ine/[l]ocal"
   echo ""
}

proj=$1

if [[ "$proj" == "m" ]]; then
   print_and_run git log --branches --no-walk --author=malin.elser@volvo.com --oneline
elif [[ "$proj" == "l" ]]; then
   print_and_run git branch --format="%(refname:short)"
else
   echo ""
   echo "Hark! An error doth arise:"
   echo ""
   print_usage
   exit 1
fi
