#!/bin/bash

print_and_run() {
   echo -e "\033[36m** Casting spell **\033[0m"
   echo -e "\033[36m$*\033[0m"   # Print command in cyan
   echo "** * * * * * * * **"
   echo ""
   "$@"                           # Execute command safely
   echo -e "\033[1;35m$*\033[0m"   # Print command in cyan
   echo -e "\033[1;35m** spell finished **\033[0m"
}

script_name=$(basename "$0")
print_usage() 
{
   echo "Usage:"
   echo "  arg1 [s]tandard/[i]nteractive"
   echo "  arg2 <branch name> or <number>"
   echo ""
   echo "Example:"
   echo "gr s develop/MT -> git fetch origin develop/MT && git rebase origin/develop/MT"
   echo "gc i develop/MT -> git rebase -i develop/MT"
   echo "gc i 3 -> git rebase -i HEAD~3"
   echo ""
}

# Check for first argument
if [[ -z "$1" ]]; then
   print_usage
   exit 1
fi

proj=$1
branch_name=$2

is_int() {
   [[ "$1" =~ ^-?[0-9]+$ ]]
}


if [ -z "$branch_name" ]; then
   echo "Hark! An error doth arise:"
   echo ""
   print_usage
   exit 1
else
   if [[ "$proj" == "s" ]]; then
      print_and_run git fetch origin $branch_name
      print_and_run git rebase origin/$branch_name
      print_and_run git submodule update --init --recursive
   elif [[ "$proj" == "i" ]]; then
      if is_int "$2"; then
         print_and_run git rebase -i HEAD~$branch_name
      else
         print_and_run git rebase -i $branch_name
      fi
   else
      echo "Hark! An error doth arise:"
      echo ""
      print_usage
      exit 1
   fi
fi
