#!/bin/bash

print_and_run() {
    echo -e "\033[36m** Casting spell **\033[0m"
    echo -e "\033[36m$*\033[0m"   # Print command in cyan
    echo "** * * * * * * * **"
    echo ""
    "$@"                           # Execute command safely
    echo -e "\033[1;35m$*\033[0m"   # Print command in cyan
    echo -e "\033[1;35m** spell finished **\033[0m"
}

script_name=$(basename "$0")
print_usage() 
{
    echo "Usage:"
    echo "  arg1 <proj>"
    echo ""
    echo "Example:"
    echo "  ${script_name} ice"
    echo "  ${script_name} bev"
    echo "  ${script_name} mule"
    echo "  ${script_name} mice"
    echo "  ${script_name} mbev"
    echo ""
}

# Check for argument
if [[ -z "$1" ]]; then
    print_usage
    exit 1
fi

proj=$1


if [[ "$proj" == "bev" ]]; then
    project="P_CCM4_T3_HMBEV"
elif [[ "$proj" == "mule" ]]; then
    project="P_CCM4_T2_HMMUL"
elif [[ "$proj" == "ice" ]]; then
    project="P_CCM4_T3_HMICE"
elif [[ "$proj" == "mice" ]]; then
    project="P_CCM4_T2_MBICE"
elif [[ "$proj" == "mbev" ]]; then
    project="P_CCM4_T2_MMBEV"
elif [[ "$proj" == "sice" ]]; then
    project="P_CCM4_T3_HSICE"

elif [[ "$proj" == "all" ]]; then
project=("P_CCM4_T2_HMMUL"
"P_CCM4_T3_HSICE"
"P_CCM4_T3_HMICE"
"P_CCM4_T3_HBICE"
"P_CCM4_T2_MBICE"
"P_CCM4_T3_HMBEV"
"P_CCM4_T2_MMBEV")
print_and_run tmux clear-history
i=0
while [ $i -lt ${#project[@]} ]; do
    print_and_run make PROJECT=${project[$i]} clean
    ((i++))   # increment index
done
i=0
while [ $i -lt ${#project[@]} ]; do
    print_and_run make PROJECT=${project[$i]} vision
    ((i++))   # increment index
done
    echo -e "\033[1;35m** search 'build did not' to find failures **\033[0m"

else
    echo "Hark! An error doth arise:"
    echo “Thy chosen project, $proj, liveth not, nor ever hath it been.”
    echo ""
    print_usage
    exit 1
fi

if [[ "$proj" != "all" ]]; then
# print_and_run make clean
print_and_run make PROJECT=${project} clean
print_and_run make PROJECT=${project} vision
fi
