#!/bin/bash

print_and_run() {
    echo -e "\033[36m** Casting spell **\033[0m"
    echo -e "\033[36m$*\033[0m"   # Print command in cyan
    echo "** * * * * * * * **"
    echo ""
    "$@"                           # Execute command safely
    echo -e "\033[1;35m$*\033[0m"   # Print command in cyan
    echo -e "\033[1;35m** spell finished **\033[0m"
}

script_name=$(basename "$0")
print_usage() 
{
    echo "Usage:"
    echo "  arg1 <proj> (ice/bev/mule)"
    echo "  arg1 <relative_path_to_component> (optional)"
    echo "  arg2 <test_filter> (optional)"
    echo ""
    echo "Example:"
    echo "  ./${script_name} ice"
    echo "  ./${script_name} bev"
    echo "  ./${script_name} mice"
    echo "  ./${script_name} mbev"
    echo "  ./${script_name} mule"
    echo ""
}

# Check for first argument
if [[ -z "$1" ]]; then
    print_usage
    exit 1
fi

proj=$1

if [[ "$proj" == "bev" ]]; then
    project="P_CCM4_T3_HMBEV"
elif [[ "$proj" == "mule" ]]; then
    project="P_CCM4_T2_HMMUL"
elif [[ "$proj" == "ice" ]]; then
    project="P_CCM4_T3_HMICE"
elif [[ "$proj" == "mice" ]]; then
    project="P_CCM4_T2_MBICE"
elif [[ "$proj" == "mbev" ]]; then
    project="P_CCM4_T2_MMBEV"
elif [[ "$proj" == "sice" ]]; then
    project="P_CCM4_T3_HSICE"

elif [[ "$proj" == "all" ]]; then
project=("P_CCM4_T2_HMMUL"
"P_CCM4_T3_HSICE"
"P_CCM4_T3_HMICE"
"P_CCM4_T3_HBICE"
"P_CCM4_T2_MBICE"
"P_CCM4_T3_HMBEV"
"P_CCM4_T2_MMBEV")
print_and_run tmux clear-history
i=0
while [ $i -lt ${#project[@]} ]; do
    print_and_run make PROJECT=${project[$i]} vecu_clean
    ((i++))   # increment index
done
i=0
while [ $i -lt ${#project[@]} ]; do
    print_and_run make PROJECT=${project[$i]} vecu
    ((i++))   # increment index
done
    echo -e "\033[1;35m** search 'build did not' to find failures **\033[0m"

else
    echo "Hark! An error doth arise:"
    echo -e "Thou hast enter’d a false project name: \033[31m\"${proj}\"\033[0m."
    echo "Prithee, choose betwixt ice, bev, mice, mbev or mule.   ^"
    echo ""
    print_usage
    exit 1
fi

if [[ "$proj" != "all" ]]; then
    # print_and_run make clean
    print_and_run make PROJECT=${project} vecu_clean
    print_and_run make PROJECT=${project} vecu
fi
